//
//  MainPresenter.swift
//  SmallWorld-iOS
//
//  Created by Carlos Villamizar on 23/11/21.
//

import Foundation

protocol MainPresentationLogic {
//    func presentSearchAcronyms(response: [Main.SearchAcronyms.Response])
//    func presentError(response: Main.Error.Response)
}

class MainPresenter: MainPresentationLogic {
    weak var viewController: MainDisplayLogic?
    /* Is the class which is responsible for presenting the object which
    is generated by the Interactor.*/
  
    // MARK: - Present SearchPost
//    func presentSearchAcronyms(response: [Main.SearchAcronyms.Response]) {
//        let viewModel = Main.SearchAcronyms.ViewModel(data: response)
//        viewController?.displaySearchAcronyms(viewModel: viewModel, on: .main)
//    }
//
    // MARK: - Present Error
//    func presentError(response: Main.Error.Response) {
//        let viewModel = Main.Error.ViewModel(error: response.error)
//        viewController?.displayError(viewModel: viewModel, on: .main)
//    }
}
