# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SmallWorld-iOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SmallWorld-iOS

  pod 'Alamofire', '~> 5.2'
  pod 'Kingfisher', '~> 6.0'

  target 'SmallWorld-iOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SmallWorld-iOSUITests' do
    # Pods for testing
  end

end
